import test from 'tape';
import { OrderEndpointConnector, RequestDispatcher } from './../../distribution/scripts';
import { reusableTesters } from './../../tools/helpers';
import { login } from './../../tools/fixtures';
import { variables } from './../../tools/values';

const instance = new OrderEndpointConnector(new RequestDispatcher(login));

test('OrderEndpointConnector#constructor', t => reusableTesters.testEndpointConnectorConstructor(t, OrderEndpointConnector));
test('OrderEndpointConnector#createItemAttribute', t => reusableTesters.testEndpointConnectorCustomMethodWithMultipleParameters(t, instance, 'createItemAttribute', [variables.examples.number, variables.examples.number, variables.empty.object]));
test('OrderEndpointConnector#createItem', t => reusableTesters.testEndpointConnectorCustomMethodWithMultipleParameters(t, instance, 'createItem', [variables.examples.number, variables.empty.object]));
test('OrderEndpointConnector#createTotal', t => reusableTesters.testEndpointConnectorCustomMethodWithMultipleParameters(t, instance, 'createTotal', [variables.examples.number, variables.empty.object]));
test('OrderEndpointConnector#create', t => reusableTesters.testEndpointConnectorCreateMethod(t, instance));
test('OrderEndpointConnector#deleteItemAttribute', t => reusableTesters.testEndpointConnectorCustomMethodWithMultipleParameters(t, instance, 'deleteItemAttribute', [variables.examples.number, variables.examples.number, variables.examples.number]));
test('OrderEndpointConnector#deleteItemProperty', t => reusableTesters.testEndpointConnectorCustomMethodWithMultipleParameters(t, instance, 'deleteItemProperty', [variables.examples.number, variables.examples.number, variables.examples.number]));
test('OrderEndpointConnector#deleteTotal', t => reusableTesters.testEndpointConnectorCustomMethodWithMultipleParameters(t, instance, 'deleteTotal', [variables.examples.number, variables.examples.number]));
test('OrderEndpointConnector#delete', t => reusableTesters.testEndpointConnectorDeleteMethod(t, instance));
test('OrderEndpointConnector#getHistory', t => reusableTesters.testEndpointConnectorCustomMethodWithRequiredParameter(t, instance, 'getHistory', variables.examples.number));
test('OrderEndpointConnector#getHistoryById', t => reusableTesters.testEndpointConnectorCustomMethodWithMultipleParameters(t, instance, 'getHistoryById', [variables.examples.number, variables.examples.number]));
test('OrderEndpointConnector#getItemAttributes', t => reusableTesters.testEndpointConnectorCustomMethodWithMultipleParameters(t, instance, 'getItemAttributes', [variables.examples.number, variables.examples.number]));
test('OrderEndpointConnector#getItemProperties', t => reusableTesters.testEndpointConnectorCustomMethodWithMultipleParameters(t, instance, 'getItemProperties', [variables.examples.number, variables.examples.number]));
test('OrderEndpointConnector#getItemAttributeById', t => reusableTesters.testEndpointConnectorCustomMethodWithMultipleParameters(t, instance, 'getItemAttributeById', [variables.examples.number, variables.examples.number, variables.examples.number]));
test('OrderEndpointConnector#getItemPropertyById', t => reusableTesters.testEndpointConnectorCustomMethodWithMultipleParameters(t, instance, 'getItemPropertyById', [variables.examples.number, variables.examples.number, variables.examples.number]));
test('OrderEndpointConnector#getItems', t => reusableTesters.testEndpointConnectorCustomMethodWithRequiredParameter(t, instance, 'getItems', variables.examples.number));
test('OrderEndpointConnector#getItemById', t => reusableTesters.testEndpointConnectorCustomMethodWithMultipleParameters(t, instance, 'getItemById', [variables.examples.number, variables.examples.number]));
test('OrderEndpointConnector#getTotals', t => reusableTesters.testEndpointConnectorCustomMethodWithRequiredParameter(t, instance, 'getTotals', variables.examples.number));
test('OrderEndpointConnector#getTotalById', t => reusableTesters.testEndpointConnectorCustomMethodWithMultipleParameters(t, instance, 'getTotalById', [variables.examples.number, variables.examples.number]));
test('OrderEndpointConnector#get', t => reusableTesters.testEndpointConnectorGetMethod(t, instance));
test('OrderEndpointConnector#getById', t => reusableTesters.testEndpointConnectorGetByIdMethod(t, instance));
test('OrderEndpointConnector#search', t => reusableTesters.testEndpointConnectorSearchMethod(t, instance));
